title: calebbrown.id.au
author: Caleb Brown
excerpt_separator: <!--break-->
permalink: /blog/:title
google_analytics: UA-12637619-1
defaults:
 - scope:
    path: "static"
   values:
     images: true
 - scope:
    path: "images"
   values:
     images: true

plugins:
 - jekyll-redirect-from
 - jekyll-feed

