title: calebbrown.id.au
author: Caleb Brown
excerpt_separator: <!--break-->
defaults:
 - scope:
    path: "static"
   values:
     images: true
 - scope:
    path: "images"
   values:
     images: true

plugins:
 - jekyll-redirect-from

